# Generated by Django 5.1.3 on 2024-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('idEncargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEncargado', models.CharField(max_length=255)),
                ('numeroTrabajador', models.CharField(max_length=20, unique=True)),
                ('bActivo', models.BooleanField(null=True)),
            ],
        ),
    ]
